=== isabella87/xrsrv/lib/statements.xsd
<?xml version="1.0" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified">

	<xsd:element name="root">
		<xsd:complexType>
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element name="module" type="moduleType" />
				<xsd:element name="include" type="includeType" />
			</xsd:choice>
		</xsd:complexType>
	</xsd:element>

	<xsd:complexType name="moduleType">
		<xsd:sequence minOccurs="0" maxOccurs="1">
			<xsd:element name="entity" type="entityType" minOccurs="0"
				maxOccurs="unbounded" />
			<xsd:element name="sql" type="sqlFragmentType" minOccurs="0"
				maxOccurs="unbounded" />
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element name="statement" type="statementType" />
				<xsd:element name="stmt" type="statementType" />
			</xsd:choice>
		</xsd:sequence>
		<xsd:attribute name="name" type="identityName" use="required" />
		<xsd:attribute name="package" type="packageName" use="optional"
			default="" />
		<xsd:attribute name="description" type="xsd:normalizedString"
			use="optional" default="" />
	</xsd:complexType>

	<xsd:complexType name="includeType">
		<xsd:attribute name="src" type="xsd:string" use="required" />
	</xsd:complexType>

	<xsd:complexType name="entityType">
		<xsd:choice minOccurs="1" maxOccurs="unbounded">
			<xsd:element name="field" type="fieldType" />
		</xsd:choice>
		<xsd:attribute name="name" type="identityName" use="required" />
		<xsd:attribute name="description" type="xsd:normalizedString"
			use="optional" default="" />
	</xsd:complexType>

	<xsd:complexType name="fieldType">
		<xsd:attribute name="name" type="identityName" use="required" />
		<xsd:attribute name="type" type="fieldTypeType" use="optional"
			default="string" />
		<xsd:attribute name="key" type="boolean" use="optional"
			default="false" />
		<xsd:attribute name="description" type="xsd:normalizedString"
			use="optional" default="" />
		<xsd:attribute name="defaultValue" type="xsd:normalizedString"
			use="optional" default="" />
	</xsd:complexType>

	<xsd:complexType name="sqlFragmentType" mixed="true">
		<xsd:attribute name="name" type="identityName" use="required" />
	</xsd:complexType>

	<xsd:complexType name="statementType" mixed="true">
		<xsd:sequence>
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element name="sqlRef" type="sqlReferenceType"
					minOccurs="0" maxOccurs="unbounded" />
				<xsd:element name="dynamic" type="dynamicStatementType"
					minOccurs="0" maxOccurs="unbounded" />
			</xsd:choice>
			<xsd:element name="parameter" type="parameterType"
				minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
		<xsd:attribute name="name" type="identityName" use="required" />
		<xsd:attribute name="allowPaging" type="boolean"
			default="auto" />
		<xsd:attribute name="commandType" type="statementCommandTypeType"
			default="text" />
		<xsd:attribute name="resultType" type="statementResultTypeType"
			default="updated-count" />
		<xsd:attribute name="entityName" type="identityName"
			use="optional" />
		<xsd:attribute name="autoKey" type="autoKeyName" use="optional" />
		<xsd:attribute name="readonly" type="boolean" default="auto" />
		<xsd:attribute name="description" type="xsd:normalizedString"
			use="optional" default="" />
	</xsd:complexType>

	<xsd:complexType name="sqlReferenceType">
		<xsd:attribute name="name" type="identityName" use="required" />
	</xsd:complexType>

	<xsd:simpleType name="statementCommandTypeType">
		<xsd:restriction base="xsd:normalizedString">
			<xsd:enumeration value="text" />
			<!-- store procedure // -->
			<xsd:enumeration value="sp" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:complexType name="dynamicStatementType">
		<xsd:choice minOccurs="1" maxOccurs="unbounded">
			<xsd:element name="isNull" type="dynamicStatementTextType" />
			<xsd:element name="isNotNull" type="dynamicStatementTextType" />
			<xsd:element name="isEmpty" type="dynamicStatementTextType" />
			<xsd:element name="isNotEmpty" type="dynamicStatementTextType" />
			<xsd:element name="isNullOrEmpty" type="dynamicStatementTextType" />
			<xsd:element name="equals" type="dynamicStatementTextType" />
			<xsd:element name="notEquals" type="dynamicStatementTextType" />
			<xsd:element name="in" type="dynamicStatementTextType" />
			<xsd:element name="notIn" type="dynamicStatementTextType" />
		</xsd:choice>
		<xsd:attribute name="prepend" type="xsd:normalizedString"
			use="optional" default="" />
		<xsd:attribute name="append" type="xsd:normalizedString"
			use="optional" default="" />
		<xsd:attribute name="joint" type="xsd:normalizedString"
			use="optional" default="AND" />
	</xsd:complexType>

	<xsd:complexType name="dynamicStatementTextType" mixed="true">
		<xsd:attribute name="parameter" type="identityName" use="required" />
		<xsd:attribute name="value" type="xsd:normalizedString"
			default="" />
	</xsd:complexType>

	<xsd:complexType name="parameterType">
		<xsd:attribute name="name" type="identityName" use="required" />
		<xsd:attribute name="type" type="parameterTypeType" use="required" />
		<xsd:attribute name="size" type="columnSizeType" use="optional"
			default="0">
		</xsd:attribute>
		<xsd:attribute name="match" type="parameterMatchType"
			default="exact" />
		<xsd:attribute name="description" type="xsd:normalizedString"
			use="optional" default="" />
	</xsd:complexType>

	<xsd:simpleType name="columnSizeType">
		<xsd:restriction base="xsd:nonNegativeInteger">
			<xsd:minInclusive fixed="true" value="0" />
			<xsd:maxInclusive fixed="true" value="4000" />
			<xsd:whiteSpace value="collapse" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="parameterTypeType">
		<xsd:restriction base="xsd:normalizedString">
			<xsd:enumeration value="string" />
			<xsd:enumeration value="int" />
			<xsd:enumeration value="integer" />
			<xsd:enumeration value="money" />
			<xsd:enumeration value="decimal" />
			<xsd:enumeration value="currency" />
			<xsd:enumeration value="datetime" />
			<xsd:enumeration value="date" />
			<xsd:enumeration value="start-date" />
			<xsd:enumeration value="start-month" />
			<xsd:enumeration value="start-year" />
			<xsd:enumeration value="end-date" />
			<xsd:enumeration value="end-month" />
			<xsd:enumeration value="end-year" />
			<xsd:enumeration value="double" />
			<xsd:enumeration value="real" />
			<xsd:enumeration value="bit" />
			<xsd:enumeration value="bool" />
			<xsd:enumeration value="boolean" />
			<xsd:enumeration value="binary" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="parameterMatchType">
		<xsd:restriction base="xsd:normalizedString">
			<xsd:enumeration value="exact" />
			<xsd:enumeration value="starts-with" />
			<xsd:enumeration value="ends-with" />
			<xsd:enumeration value="contains" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="fieldTypeType">
		<xsd:restriction base="xsd:normalizedString">
			<xsd:enumeration value="string" />
			<xsd:enumeration value="big-string" />
			<xsd:enumeration value="int" />
			<xsd:enumeration value="integer" />
			<xsd:enumeration value="money" />
			<xsd:enumeration value="decimal" />
			<xsd:enumeration value="currency" />
			<xsd:enumeration value="datetime" />
			<xsd:enumeration value="real" />
			<xsd:enumeration value="double" />
			<xsd:enumeration value="bit" />
			<xsd:enumeration value="bool" />
			<xsd:enumeration value="boolean" />
			<xsd:enumeration value="binary" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="statementResultTypeType">
		<xsd:restriction base="xsd:normalizedString">
			<!-- Entity -->
			<xsd:enumeration value="entities" />
			<xsd:enumeration value="entity" />
			<!-- Scalar -->
			<xsd:enumeration value="string" />
			<xsd:enumeration value="int" />
			<xsd:enumeration value="integer" />
			<xsd:enumeration value="money" />
			<xsd:enumeration value="decimal" />
			<xsd:enumeration value="currency" />
			<xsd:enumeration value="datetime" />
			<xsd:enumeration value="date" />
			<xsd:enumeration value="double" />
			<xsd:enumeration value="bit" />
			<xsd:enumeration value="bool" />
			<xsd:enumeration value="boolean" />
			<xsd:enumeration value="binary" />
			<xsd:enumeration value="array" />
			<!-- List -->
			<xsd:enumeration value="list-string" />
			<xsd:enumeration value="list-int" />
			<xsd:enumeration value="list-integer" />
			<xsd:enumeration value="list-money" />
			<xsd:enumeration value="list-decimal" />
			<xsd:enumeration value="list-currency" />
			<xsd:enumeration value="list-datetime" />
			<xsd:enumeration value="list-date" />
			<xsd:enumeration value="list-double" />
			<xsd:enumeration value="list-bit" />
			<xsd:enumeration value="list-bool" />
			<xsd:enumeration value="list-boolean" />
			<xsd:enumeration value="list-binary" />
			<xsd:enumeration value="list-array" />
			<!-- Update -->
			<xsd:enumeration value="uc" />
			<xsd:enumeration value="updated-count" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="boolean">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="auto" />
			<xsd:enumeration value="0" />
			<xsd:enumeration value="1" />
			<xsd:enumeration value="yes" />
			<xsd:enumeration value="no" />
			<xsd:enumeration value="true" />
			<xsd:enumeration value="false" />
			<xsd:enumeration value="on" />
			<xsd:enumeration value="off" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="text">
		<xsd:restriction base="xsd:string">
			<xsd:minLength value="1" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="identityName">
		<xsd:restriction base="xsd:normalizedString">
			<xsd:minLength value="1" />
			<xsd:pattern value="[\w_]+" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="autoKeyName">
		<xsd:restriction base="xsd:normalizedString">
			<xsd:minLength value="1" />
			<xsd:pattern value="([\w_]+)|\*" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="packageName">
		<xsd:restriction base="xsd:normalizedString">
			<xsd:minLength value="0" />
			<xsd:pattern value="[\w_]*" />
		</xsd:restriction>
	</xsd:simpleType>
</xsd:schema>

=== isabella87/xrsrv/src/MajorProduct.xml
<?xml version="1.0" encoding="utf-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../lib/statements.xsd">
	<module description="major_product_ module" name="major_product">
       <entity description="product_info table" name="product_info">
			<field name="mp_id" type="int" />
			<field name="pro_name" type="string" />
            <field name="pro_no" type="string" />
			<field name="price" type="decimal" />
			<field name="type" type="string" />
			<field name="status" type="int" />	
            <field name="visible" type="int" />
			<field name="creator" type="string" />
			<field name="create_time" type="datetime" />
			<field name="updator" type="string" />
			<field name="update_time" type="datetime" />
		</entity>
		
		<entity description="product_info table" name="product_info_not_con_id">
			<field name="pro_name" type="string" />
            <field name="pro_no" type="string" />
			<field name="price" type="decimal" />
			<field name="type" type="string" />
			<field name="status" type="int" />	
            <field name="visible" type="int" />
			<field name="creator" type="string" />
			<field name="create_time" type="datetime" />
			<field name="updator" type="string" />
			<field name="update_time" type="datetime" />
		</entity>
		
		 <entity description="product_info_and_file_id table" name="product_info_and_file_id">
			<field name="mp_id" type="int" />
			<field name="pro_name" type="string" />
            <field name="pro_no" type="string" />
			<field name="price" type="decimal" />
			<field name="type" type="string" />
			<field name="status" type="int" />	
            <field name="visible" type="int" />
			<field name="creator" type="string" />
			<field name="create_time" type="datetime" />
			<field name="updator" type="string" />
			<field name="update_time" type="datetime" />
			<field name="file_id" type="int" />
		</entity>
		
		 <entity description="bg_product_info table" name="bg_product_info">
			<field name="mp_id" type="int" />
			<field name="pro_name" type="string" />
            <field name="pro_no" type="string" />
			<field name="price" type="decimal" />
			<field name="type" type="string" />
			<field name="status" type="int" />	
            <field name="visible" type="int" />
			<field name="creator" type="string" />
			<field name="create_time" type="datetime" />
			<field name="updator" type="string" />
			<field name="update_time" type="datetime" />
			<field name="has_file" type="int" />
		</entity>
		
		<entity description="file_info_ table" name="file_info">
			<field name="file_id" type="int" />
			<field name="file_type" type="int" />
			<field name="object_id" type="int" />
            <field name="name" type="string" />
			<field name="last_write_time" type="datetime" />
			<field name="description" type="string" />
			<field name="summary" type="string" />
			<field name="attrs" type="int" />	
            <field name="parent_id" type="int" />
            <field name="deleted" type="int" />
		</entity>
		
		<entity description="file_content_ table" name="file_content">
			<field name="file_id" type="int" />
			<field name="content" type="string" />
		</entity>
		
		<entity description="file_path_ table" name="file_path">
			<field name="a_id" type="int" />
			<field name="d_id" type="int" />
            <field name="depth" type="int" />
		</entity>
		
		<statement name="create_product_info" resultType="uc" autoKey="mp_id">
			<![CDATA[INSERT INTO MAJOR_PRODUCT({product_info_not_con_id})
				     VALUES(#pro_name#, #pro_no#, #price#, #type# , #status#, #visible#, #creator#, #create_time#,#updator#, #update_time#)
			]]>
			<parameter name="pro_name" type="string" />
			<parameter name="pro_no" type="string" />
			<parameter name="price" type="decimal" />
			<parameter name="type" type="string" />
			<parameter name="status" type="int" />
			<parameter name="visible" type="int" />
			<parameter name="creator" type="string" />
			<parameter name="create_time" type="datetime" />
			<parameter name="updator" type="string" />
			<parameter name="update_time" type="datetime" />
			
		</statement>
		
		<statement name="update_product_info" resultType="uc">
			<![CDATA[UPDATE MAJOR_PRODUCT
					 SET  
						PRODUCT_NAME = #pro_name#,
					 	PRICE = #price#, 
					 	TYPE=#type#, 
					 	UPDATOR=#updator#,
					  	UPDATE_TIME=#update_time#,
					  	STATUS= #status#, 
					   	VISIBLE=#visible#
					 WHERE MP_ID = #mp_id#
			]]>
			<parameter name="mp_id" type="int" />
			<parameter name="pro_name" type="string" />
			<parameter name="price" type="decimal" />
			<parameter name="type" type="string" />
			<parameter name="status" type="int" />
			<parameter name="visible" type="int" />
			<parameter name="updator" type="string" />
			<parameter name="update_time" type="datetime" />
		</statement>
		
		<statement name="update_product_info_status" resultType="uc">
			<![CDATA[UPDATE MAJOR_PRODUCT
					 SET  
					 	UPDATOR=#updator#,
					  	UPDATE_TIME=#update_time#,
					  	STATUS= #status# 
					 WHERE MP_ID = #mp_id# AND STATUS = #old_status#
			]]>
			<parameter name="mp_id" type="int" />
			<parameter name="status" type="int" />
			<parameter name="old_status" type="int" />
			<parameter name="updator" type="string" />
			<parameter name="update_time" type="datetime" />
		</statement>
		
		<statement name="query_product_info_list_for_bg" resultType="entities"
			entityName="bg_product_info">
			<![CDATA[SELECT MP.MP_ID,MP.PRO_NAME,MP.PRO_NO,MP.PRICE,MP.TYPE,MP.STATUS,MP.VISIBLE,
					MP.CREATOR,MP.CREATE_TIME,MP.UPDATOR,MP.UPDATE_TIME,
					CASE WHEN FF.FILE_ID IS NOT NULL THEN 1 ELSE 0 END HAS_FILE
	 				 FROM MAJOR_PRODUCT  MP
	 				 LEFT JOIN FS_FILE FF ON FF.OBJECT_ID = MP.MP_ID
					 WHERE VISIBLE = 1
			]]>
			<dynamic prepend="and">
				<isNotEmpty parameter="type">
					<![CDATA[MP.TYPE = #type#]]>
				</isNotEmpty>
				<isNotEmpty parameter="status">
					<![CDATA[MP.STATUS = #status#]]>
				</isNotEmpty>
				<isNotEmpty parameter="start_time">
					<![CDATA[MP.CREATE_TIME >= #start_time#]]>
				</isNotEmpty>
				<isNotEmpty parameter="end_time">
					<![CDATA[MP.CREATE_TIME <= #end_time#]]>
				</isNotEmpty>
				<isNotEmpty parameter="search_key">
					<![CDATA[(MP.PRO_NAME LIKE #search_key# OR MP.TYPE LIKE #search_key#)]]>
				</isNotEmpty>
			</dynamic>
			<![CDATA[ORDER BY MP.MP_ID DESC]]>
			<parameter name="type" type="string" />
			<parameter name="status" type="int" />
			<parameter name="start_time" type="datetime" />
			<parameter name="end_time" type="datetime" />
			<parameter name="search_key" type="string" match="contains" />
		</statement>
		
		<statement name="query_product_info_list" resultType="entities"
			entityName="product_info">
			<![CDATA[SELECT {product_info}
	 				 FROM MAJOR_PRODUCT 
					 WHERE VISIBLE = 1
			]]>
			<dynamic prepend="and">
				<isNotEmpty parameter="type">
					<![CDATA[TYPE = #type#]]>
				</isNotEmpty>
				<isNotEmpty parameter="status">
					<![CDATA[STATUS = #status#]]>
				</isNotEmpty>
				<isNotEmpty parameter="start_time">
					<![CDATA[CREATE_TIME >= #start_time#]]>
				</isNotEmpty>
				<isNotEmpty parameter="end_time">
					<![CDATA[CREATE_TIME <= #end_time#]]>
				</isNotEmpty>
				<isNotEmpty parameter="search_key">
					<![CDATA[(PRO_NAME LIKE #search_key# OR TYPE LIKE #search_key#)]]>
				</isNotEmpty>
			</dynamic>
			<![CDATA[ORDER BY MP_ID DESC]]>
			<parameter name="type" type="string" />
			<parameter name="status" type="int" />
			<parameter name="start_time" type="datetime" />
			<parameter name="end_time" type="datetime" />
			<parameter name="search_key" type="string" match="contains" />
		</statement>
		
		<statement name="query_product_info_list_count" resultType="int">
			<![CDATA[SELECT count(1)
					 FROM MAJOR_PRODUCT 
					 WHERE VISIBLE = 1
			]]>
			<dynamic prepend="and">
				<isNotEmpty parameter="type">
					<![CDATA[TYPE = #type#]]>
				</isNotEmpty>
				<isNotEmpty parameter="status">
					<![CDATA[STATUS = #status#]]>
				</isNotEmpty>
				<isNotEmpty parameter="start_time">
					<![CDATA[CREATE_TIME >= #start_time#]]>
				</isNotEmpty>
				<isNotEmpty parameter="end_time">
					<![CDATA[CREATE_TIME <= #end_time#]]>
				</isNotEmpty>
				<isNotEmpty parameter="search_key">
					<![CDATA[(PRO_NAME LIKE #search_key# OR TYPE LIKE #search_key#)]]>
				</isNotEmpty>
			</dynamic>
			<parameter name="type" type="string" />
			<parameter name="status" type="int" />
			<parameter name="start_time" type="datetime" />
			<parameter name="end_time" type="datetime" />
			<parameter name="search_key" type="string" match="contains" />
		</statement>
		
		<statement name="exist_product_of_pro_no" resultType="boolean">
			<![CDATA[SELECT CASE WHEN EXISTS (SELECT MP_ID
					 FROM MAJOR_PRODUCT 
					 WHERE PRO_NO = #pro_no#) THEN 1
					 ELSE 0 END
					 FROM DUAL
			]]>
			<parameter name="pro_no" type="string" />
		</statement>
		
		<statement name="query_product_info" resultType="entity"
			entityName="product_info_and_file_id">
			<![CDATA[SELECT MP.MP_ID,MP.PRO_NAME,MP.PRO_NO,MP.PRICE,MP.TYPE,MP.STATUS,MP.VISIBLE,
					MP.CREATOR,MP.CREATE_TIME,MP.UPDATOR,MP.UPDATE_TIME,
					FF.FILE_ID
	 				 FROM MAJOR_PRODUCT  MP
	 				 LEFT JOIN FS_FILE FF ON FF.OBJECT_ID = MP.MP_ID
					 WHERE MP.MP_ID = #mp_id#
			]]>
			<parameter name="mp_id" type="int" />
		</statement>
	
	<statement name="query_file_info_with_max_id" resultType="entity"
			entityName="file_info">
			<![CDATA[SELECT {file_info}
					 FROM FS_FILE FF
					 WHERE FF.FILE_ID = (SELECT MAX(FILE_ID) FROM FS_FILE WHERE OBJECT_ID = #mp_id#)
			]]>
			<parameter name="mp_id" type="int" />
		</statement>
	
		<statement name="delete_product_info" resultType="uc">
			<![CDATA[DELETE 
					 FROM MAJOR_PRODUCT
					 WHERE MP_ID = #mp_id# 
			]]>
			<parameter name="mp_id" type="int" />
		</statement>
		
	</module>
</root>

=== isabella87/xrsrv/src/MaintenanceMan.xml
<?xml version="1.0" encoding="utf-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../lib/statements.xsd">
	<module description="maintenance_man_ module" name="maintenance_man">
       <entity description="worker_info table" name="worker_info">
			<field name="mm_id" type="int" />
			<field name="mm_name" type="string" />
            <field name="mm_no" type="string" />
			<field name="mm_level" type="string" />
			<field name="mm_mobile" type="string" />
			<field name="mm_intro" type="string" />	
            <field name="enable" type="int" />
			<field name="creator" type="string" />
			<field name="create_time" type="datetime" />
			<field name="updator" type="string" />
			<field name="update_time" type="datetime" />
		</entity>
		<entity description="worker_info table" name="worker_info_not_con_id">
			<field name="mm_name" type="string" />
            <field name="mm_no" type="string" />
			<field name="mm_level" type="string" />
			<field name="mm_mobile" type="string" />
			<field name="mm_intro" type="string" />	
            <field name="enable" type="int" />
			<field name="creator" type="string" />
			<field name="create_time" type="datetime" />
			<field name="updator" type="string" />
			<field name="update_time" type="datetime" />
		</entity>
		
		 <entity description="worker_info_and_file_id table" name="worker_info_and_file_id">
			<field name="mm_id" type="int" />
			<field name="mm_name" type="string" />
            <field name="mm_no" type="string" />
			<field name="mm_level" type="string" />
			<field name="mm_mobile" type="string" />
			<field name="mm_intro" type="string" />	
            <field name="enable" type="int" />
			<field name="creator" type="string" />
			<field name="create_time" type="datetime" />
			<field name="updator" type="string" />
			<field name="update_time" type="datetime" />
			<field name="file_id" type="int" />
		</entity>
		
		 <entity description="bg_worker_info table" name="bg_worker_info">
			<field name="mm_id" type="int" />
			<field name="mm_name" type="string" />
            <field name="mm_no" type="string" />
			<field name="mm_level" type="string" />
			<field name="mm_mobile" type="string" />
			<field name="mm_intro" type="string" />	
            <field name="enable" type="int" />
			<field name="creator" type="string" />
			<field name="create_time" type="datetime" />
			<field name="updator" type="string" />
			<field name="update_time" type="datetime" />
			<field name="has_file" type="int" />
		</entity>
		
		<statement name="create_worker_info" resultType="uc" autoKey="mm_id">
			<![CDATA[INSERT INTO MAINTENANCE_MAN({worker_info_not_con_id})
				     VALUES( #mm_name#, #mm_no#, #mm_level#, #mm_mobile# , #mm_intro#, #enable#, #creator#, #create_time#,#updator#, #update_time#)
			]]>
			<parameter name="mm_name" type="string" />
			<parameter name="mm_no" type="string" />
			<parameter name="mm_level" type="string" />
			<parameter name="mm_mobile" type="string" />
			<parameter name="mm_intro" type="string" />
			<parameter name="enable" type="int" />
			<parameter name="creator" type="string" />
			<parameter name="create_time" type="datetime" />
			<parameter name="updator" type="string" />
			<parameter name="update_time" type="datetime" />
			
		</statement>
		
		<statement name="update_worker_info_mm_no" resultType="uc">
			<![CDATA[UPDATE MAINTENANCE_MAN
					 SET  
					 	MM_NO = #mm_no#
					 WHERE MM_ID = #mm_id#
			]]>
			<parameter name="mm_id" type="int" />
			<parameter name="mm_no" type="string" />
		</statement>
		
		<statement name="update_worker_info" resultType="uc">
			<![CDATA[UPDATE MAINTENANCE_MAN
					 SET  
						MM_NAME = #mm_name#,
					 	MM_NO = #mm_no#, 
					 	MM_LEVEL=#mm_level#, 
					 	MM_MOBILE=#mm_mobile#, 
					 	MM_INTRO=#mm_intro#, 
					 	UPDATOR=#updator#,
					  	UPDATE_TIME=#update_time#,
					  	ENABLE= #enable#, 
					 WHERE MM_ID = #mm_id#
			]]>
			<parameter name="mm_id" type="int" />
			<parameter name="mm_name" type="string" />
			<parameter name="mm_no" type="string" />
			<parameter name="mm_level" type="string" />
			<parameter name="mm_mobile" type="string" />
			<parameter name="mm_intro" type="string" />
			<parameter name="enable" type="int" />
			<parameter name="updator" type="string" />
			<parameter name="update_time" type="datetime" />
		</statement>
		
		<statement name="update_worker_info_status" resultType="uc">
			<![CDATA[UPDATE MAINTENANCE_MAN
					 SET  
					 	UPDATOR=#updator#,
					  	UPDATE_TIME=#update_time#,
					  	ENABLE= #enable# 
					 WHERE MM_ID = #mm_id# AND ENABLE = #old_enable#
			]]>
			<parameter name="mm_id" type="int" />
			<parameter name="enable" type="int" />
			<parameter name="old_enable" type="int" />
			<parameter name="updator" type="string" />
			<parameter name="update_time" type="datetime" />
		</statement>
		
		<statement name="query_worker_info_list_for_bg" resultType="entities"
			entityName="bg_worker_info">
			<![CDATA[SELECT MM.MM_ID,MM.MM_NAME,MM.MM_NO,MM.MM_LEVEL,MM.MM_MOBILE,MM.MM_INTRO,MM.ENABLE,
					MM.CREATOR,MM.CREATE_TIME,MM.UPDATOR,MM.UPDATE_TIME,
					CASE WHEN FF.FILE_ID IS NOT NULL THEN 1 ELSE 0 END HAS_FILE
	 				 FROM MAINTENANCE_MAN  MM
	 				 LEFT JOIN FS_FILE FF ON FF.OBJECT_ID = MM.MM_ID
					 WHERE 1 = 1
			]]>
			<dynamic prepend="and">
				<isNotEmpty parameter="enable">
					<![CDATA[MM.ENABLE = #enable#]]>
				</isNotEmpty>
				<isNotEmpty parameter="start_time">
					<![CDATA[MM.CREATE_TIME >= #start_time#]]>
				</isNotEmpty>
				<isNotEmpty parameter="end_time">
					<![CDATA[MM.CREATE_TIME <= #end_time#]]>
				</isNotEmpty>
				<isNotEmpty parameter="search_key">
					<![CDATA[(MM.MM_NAME LIKE #search_key# OR MM.MM_MOBILE LIKE #search_key#)]]>
				</isNotEmpty>
			</dynamic>
			<![CDATA[ORDER BY MM.MM_ID DESC]]>
			<parameter name="enable" type="int" />
			<parameter name="start_time" type="datetime" />
			<parameter name="end_time" type="datetime" />
			<parameter name="search_key" type="string" match="contains" />
		</statement>
		
		<statement name="query_worker_info_list" resultType="entities"
			entityName="worker_info_and_file_id">
			<![CDATA[SELECT MM.MM_ID,MM.MM_NAME,MM.MM_NO,MM.MM_LEVEL,MM.MM_MOBILE,MM.MM_INTRO,MM.ENABLE,
					MM.CREATOR,MM.CREATE_TIME,MM.UPDATOR,MM.UPDATE_TIME,FF.FILE_ID
	 				 FROM MAINTENANCE_MAN MM
	 				  LEFT JOIN FS_FILE FF ON FF.OBJECT_ID = MM.MM_ID
					 WHERE 1 = 1 
			]]>
			<dynamic prepend="and">
				<isNotEmpty parameter="enable">
					<![CDATA[MM.ENABLE = #enable#]]>
				</isNotEmpty>
				<isNotEmpty parameter="start_time">
					<![CDATA[MM.CREATE_TIME >= #start_time#]]>
				</isNotEmpty>
				<isNotEmpty parameter="end_time">
					<![CDATA[MM.CREATE_TIME <= #end_time#]]>
				</isNotEmpty>
				<isNotEmpty parameter="search_key">
					<![CDATA[(MM.MM_NAME LIKE #search_key# OR MM.MM_MOBILE LIKE #search_key#)]]>
				</isNotEmpty>
			</dynamic>
			<![CDATA[ORDER BY MM.MM_ID DESC]]>
			<parameter name="enable" type="int" />
			<parameter name="start_time" type="datetime" />
			<parameter name="end_time" type="datetime" />
			<parameter name="search_key" type="string" match="contains" />
		</statement>
		
		<statement name="query_worker_info_list_count" resultType="int">
			<![CDATA[SELECT count(1)
					 FROM MAINTENANCE_MAN 
					 WHERE 1 = 1 
			]]>
			<dynamic prepend="and">
				<isNotEmpty parameter="enable">
					<![CDATA[ENABLE = #enable#]]>
				</isNotEmpty>
				<isNotEmpty parameter="start_time">
					<![CDATA[CREATE_TIME >= #start_time#]]>
				</isNotEmpty>
				<isNotEmpty parameter="end_time">
					<![CDATA[CREATE_TIME <= #end_time#]]>
				</isNotEmpty>
				<isNotEmpty parameter="search_key">
					<![CDATA[(MM_NAME LIKE #search_key# OR MM_MOBILE LIKE #search_key#)]]>
				</isNotEmpty>
			</dynamic>
			<parameter name="enable" type="int" />
			<parameter name="start_time" type="datetime" />
			<parameter name="end_time" type="datetime" />
			<parameter name="search_key" type="string" match="contains" />
		</statement>
		
		<statement name="exist_worker_info_of_mm_no" resultType="boolean">
			<![CDATA[SELECT CASE WHEN EXISTS (SELECT MM_ID
					 FROM MAINTENANCE_MAN 
					 WHERE MM_NO = #mm_no#) THEN 1
					 ELSE 0 END
					 FROM DUAL
			]]>
			<parameter name="mm_no" type="string" />
		</statement>
		
		<statement name="query_worker_info" resultType="entity"
			entityName="worker_info_and_file_id">
			<![CDATA[SELECT MM.MM_ID,MM.MM_NAME,MM.MM_NO,MM.MM_LEVEL,MM.MM_MOBILE,MM.MM_INTRO,MM.ENABLE,
					MM.CREATOR,MM.CREATE_TIME,MM.UPDATOR,MM.UPDATE_TIME,
					FF.FILE_ID
	 				 FROM MAINTENANCE_MAN  MM
	 				 LEFT JOIN FS_FILE FF ON FF.OBJECT_ID = MM.MM_ID
					 WHERE MM.MM_ID = #mm_id#
			]]>
			<parameter name="mm_id" type="int" />
		</statement>
	
	<statement name="query_file_info_with_max_mm_id" resultType="entity"
			entityName="file_info">
			<![CDATA[SELECT FILE_ID,FILE_TYPE,OBJECT_ID,NAME,LAST_WRITE_TIME,DESCRIPTION,SUMMARY,ATTRS,PARENT_ID,DELETED
					 FROM FS_FILE FF
					 WHERE FF.FILE_ID = (SELECT MAX(FILE_ID) FROM FS_FILE WHERE OBJECT_ID = #mm_id#)
			]]>
			<parameter name="mm_id" type="int" />
		</statement>
	
		<statement name="delete_worker_info" resultType="uc">
			<![CDATA[DELETE 
					 FROM MAINTENANCE_MAN
					 WHERE MM_ID = #mm_id# 
			]]>
			<parameter name="mm_id" type="int" />
		</statement>
		
	</module>
</root>
