=== isabella87/xrsrv/lib/statements.xsd
<?xml version="1.0" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified">

	<xsd:element name="root">
		<xsd:complexType>
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element name="module" type="moduleType" />
				<xsd:element name="include" type="includeType" />
			</xsd:choice>
		</xsd:complexType>
	</xsd:element>

	<xsd:complexType name="moduleType">
		<xsd:sequence minOccurs="0" maxOccurs="1">
			<xsd:element name="entity" type="entityType" minOccurs="0"
				maxOccurs="unbounded" />
			<xsd:element name="sql" type="sqlFragmentType" minOccurs="0"
				maxOccurs="unbounded" />
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element name="statement" type="statementType" />
				<xsd:element name="stmt" type="statementType" />
			</xsd:choice>
		</xsd:sequence>
		<xsd:attribute name="name" type="identityName" use="required" />
		<xsd:attribute name="package" type="packageName" use="optional"
			default="" />
		<xsd:attribute name="description" type="xsd:normalizedString"
			use="optional" default="" />
	</xsd:complexType>

	<xsd:complexType name="includeType">
		<xsd:attribute name="src" type="xsd:string" use="required" />
	</xsd:complexType>

	<xsd:complexType name="entityType">
		<xsd:choice minOccurs="1" maxOccurs="unbounded">
			<xsd:element name="field" type="fieldType" />
		</xsd:choice>
		<xsd:attribute name="name" type="identityName" use="required" />
		<xsd:attribute name="description" type="xsd:normalizedString"
			use="optional" default="" />
	</xsd:complexType>

	<xsd:complexType name="fieldType">
		<xsd:attribute name="name" type="identityName" use="required" />
		<xsd:attribute name="type" type="fieldTypeType" use="optional"
			default="string" />
		<xsd:attribute name="key" type="boolean" use="optional"
			default="false" />
		<xsd:attribute name="description" type="xsd:normalizedString"
			use="optional" default="" />
		<xsd:attribute name="defaultValue" type="xsd:normalizedString"
			use="optional" default="" />
	</xsd:complexType>

	<xsd:complexType name="sqlFragmentType" mixed="true">
		<xsd:attribute name="name" type="identityName" use="required" />
	</xsd:complexType>

	<xsd:complexType name="statementType" mixed="true">
		<xsd:sequence>
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element name="sqlRef" type="sqlReferenceType"
					minOccurs="0" maxOccurs="unbounded" />
				<xsd:element name="dynamic" type="dynamicStatementType"
					minOccurs="0" maxOccurs="unbounded" />
			</xsd:choice>
			<xsd:element name="parameter" type="parameterType"
				minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
		<xsd:attribute name="name" type="identityName" use="required" />
		<xsd:attribute name="allowPaging" type="boolean"
			default="auto" />
		<xsd:attribute name="commandType" type="statementCommandTypeType"
			default="text" />
		<xsd:attribute name="resultType" type="statementResultTypeType"
			default="updated-count" />
		<xsd:attribute name="entityName" type="identityName"
			use="optional" />
		<xsd:attribute name="autoKey" type="autoKeyName" use="optional" />
		<xsd:attribute name="readonly" type="boolean" default="auto" />
		<xsd:attribute name="description" type="xsd:normalizedString"
			use="optional" default="" />
	</xsd:complexType>

	<xsd:complexType name="sqlReferenceType">
		<xsd:attribute name="name" type="identityName" use="required" />
	</xsd:complexType>

	<xsd:simpleType name="statementCommandTypeType">
		<xsd:restriction base="xsd:normalizedString">
			<xsd:enumeration value="text" />
			<!-- store procedure // -->
			<xsd:enumeration value="sp" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:complexType name="dynamicStatementType">
		<xsd:choice minOccurs="1" maxOccurs="unbounded">
			<xsd:element name="isNull" type="dynamicStatementTextType" />
			<xsd:element name="isNotNull" type="dynamicStatementTextType" />
			<xsd:element name="isEmpty" type="dynamicStatementTextType" />
			<xsd:element name="isNotEmpty" type="dynamicStatementTextType" />
			<xsd:element name="isNullOrEmpty" type="dynamicStatementTextType" />
			<xsd:element name="equals" type="dynamicStatementTextType" />
			<xsd:element name="notEquals" type="dynamicStatementTextType" />
			<xsd:element name="in" type="dynamicStatementTextType" />
			<xsd:element name="notIn" type="dynamicStatementTextType" />
		</xsd:choice>
		<xsd:attribute name="prepend" type="xsd:normalizedString"
			use="optional" default="" />
		<xsd:attribute name="append" type="xsd:normalizedString"
			use="optional" default="" />
		<xsd:attribute name="joint" type="xsd:normalizedString"
			use="optional" default="AND" />
	</xsd:complexType>

	<xsd:complexType name="dynamicStatementTextType" mixed="true">
		<xsd:attribute name="parameter" type="identityName" use="required" />
		<xsd:attribute name="value" type="xsd:normalizedString"
			default="" />
	</xsd:complexType>

	<xsd:complexType name="parameterType">
		<xsd:attribute name="name" type="identityName" use="required" />
		<xsd:attribute name="type" type="parameterTypeType" use="required" />
		<xsd:attribute name="size" type="columnSizeType" use="optional"
			default="0">
		</xsd:attribute>
		<xsd:attribute name="match" type="parameterMatchType"
			default="exact" />
		<xsd:attribute name="description" type="xsd:normalizedString"
			use="optional" default="" />
	</xsd:complexType>

	<xsd:simpleType name="columnSizeType">
		<xsd:restriction base="xsd:nonNegativeInteger">
			<xsd:minInclusive fixed="true" value="0" />
			<xsd:maxInclusive fixed="true" value="4000" />
			<xsd:whiteSpace value="collapse" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="parameterTypeType">
		<xsd:restriction base="xsd:normalizedString">
			<xsd:enumeration value="string" />
			<xsd:enumeration value="int" />
			<xsd:enumeration value="integer" />
			<xsd:enumeration value="money" />
			<xsd:enumeration value="decimal" />
			<xsd:enumeration value="currency" />
			<xsd:enumeration value="datetime" />
			<xsd:enumeration value="date" />
			<xsd:enumeration value="start-date" />
			<xsd:enumeration value="start-month" />
			<xsd:enumeration value="start-year" />
			<xsd:enumeration value="end-date" />
			<xsd:enumeration value="end-month" />
			<xsd:enumeration value="end-year" />
			<xsd:enumeration value="double" />
			<xsd:enumeration value="real" />
			<xsd:enumeration value="bit" />
			<xsd:enumeration value="bool" />
			<xsd:enumeration value="boolean" />
			<xsd:enumeration value="binary" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="parameterMatchType">
		<xsd:restriction base="xsd:normalizedString">
			<xsd:enumeration value="exact" />
			<xsd:enumeration value="starts-with" />
			<xsd:enumeration value="ends-with" />
			<xsd:enumeration value="contains" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="fieldTypeType">
		<xsd:restriction base="xsd:normalizedString">
			<xsd:enumeration value="string" />
			<xsd:enumeration value="big-string" />
			<xsd:enumeration value="int" />
			<xsd:enumeration value="integer" />
			<xsd:enumeration value="money" />
			<xsd:enumeration value="decimal" />
			<xsd:enumeration value="currency" />
			<xsd:enumeration value="datetime" />
			<xsd:enumeration value="real" />
			<xsd:enumeration value="double" />
			<xsd:enumeration value="bit" />
			<xsd:enumeration value="bool" />
			<xsd:enumeration value="boolean" />
			<xsd:enumeration value="binary" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="statementResultTypeType">
		<xsd:restriction base="xsd:normalizedString">
			<!-- Entity -->
			<xsd:enumeration value="entities" />
			<xsd:enumeration value="entity" />
			<!-- Scalar -->
			<xsd:enumeration value="string" />
			<xsd:enumeration value="int" />
			<xsd:enumeration value="integer" />
			<xsd:enumeration value="money" />
			<xsd:enumeration value="decimal" />
			<xsd:enumeration value="currency" />
			<xsd:enumeration value="datetime" />
			<xsd:enumeration value="date" />
			<xsd:enumeration value="double" />
			<xsd:enumeration value="bit" />
			<xsd:enumeration value="bool" />
			<xsd:enumeration value="boolean" />
			<xsd:enumeration value="binary" />
			<xsd:enumeration value="array" />
			<!-- List -->
			<xsd:enumeration value="list-string" />
			<xsd:enumeration value="list-int" />
			<xsd:enumeration value="list-integer" />
			<xsd:enumeration value="list-money" />
			<xsd:enumeration value="list-decimal" />
			<xsd:enumeration value="list-currency" />
			<xsd:enumeration value="list-datetime" />
			<xsd:enumeration value="list-date" />
			<xsd:enumeration value="list-double" />
			<xsd:enumeration value="list-bit" />
			<xsd:enumeration value="list-bool" />
			<xsd:enumeration value="list-boolean" />
			<xsd:enumeration value="list-binary" />
			<xsd:enumeration value="list-array" />
			<!-- Update -->
			<xsd:enumeration value="uc" />
			<xsd:enumeration value="updated-count" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="boolean">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="auto" />
			<xsd:enumeration value="0" />
			<xsd:enumeration value="1" />
			<xsd:enumeration value="yes" />
			<xsd:enumeration value="no" />
			<xsd:enumeration value="true" />
			<xsd:enumeration value="false" />
			<xsd:enumeration value="on" />
			<xsd:enumeration value="off" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="text">
		<xsd:restriction base="xsd:string">
			<xsd:minLength value="1" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="identityName">
		<xsd:restriction base="xsd:normalizedString">
			<xsd:minLength value="1" />
			<xsd:pattern value="[\w_]+" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="autoKeyName">
		<xsd:restriction base="xsd:normalizedString">
			<xsd:minLength value="1" />
			<xsd:pattern value="([\w_]+)|\*" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="packageName">
		<xsd:restriction base="xsd:normalizedString">
			<xsd:minLength value="0" />
			<xsd:pattern value="[\w_]*" />
		</xsd:restriction>
	</xsd:simpleType>
</xsd:schema>

=== isabella87/xrsrv/src/AccUserRegPwdHistory.xml
<?xml version="1.0" encoding="utf-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../lib/statements.xsd">
	<module description="acc_user_reg_pwd_history module" name="acc_user_reg_pwd_history">
		<entity  description="acc_user_reg_pwd_history table" name="acc_user_reg_pwd_history">
			<field name="operator" type="int"/>
			<field name="operate_time" type="datetime"/>
			<field name="source" type="int"/>
			<field name="vcode" type="string"/>
		</entity>
	
	   <statement name="create_acc_user_reg_pwd_history" resultType="uc" autoKey="id">
			<![CDATA[INSERT INTO ACC_USER_REG_PWD_HISTORY ({acc_user_reg_pwd_history})
		             VALUES(#operator#, SYSDATE(), #source#, #vcode#)]]>
			<parameter name="operator" type="int"/>
			<parameter name="source" type="int"/>
		    <parameter name="vcode" type="string"/>
		</statement>
		
		<statement name="query_acc_user_reg_pwd_history_by_id" resultType="entity" entityName="acc_user_reg_pwd_history">
			<![CDATA[SELECT {acc_user_reg_pwd_history} FROM ACC_USER_REG_PWD_HISTORY WHERE ID = #id#]]>
			<parameter name="id" type="int"/>
		</statement>
	</module>
</root>

=== isabella87/xrsrv/src/ZfbOrder.xml
<?xml version="1.0" encoding="utf-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../lib/statements.xsd">
	<module description="zfb_order_ module" name="zfb_order">
       <entity description="zfb_order_info table" name="zfb_order_info">
			<field name="zo_id" type="int" />
			<field name="subject" type="string" />
			<field name="body" type="string" />
			<field name="out_trade_no" type="string" />
			<field name="timeout_express" type="string" />
			<field name="time_expire" type="string" />
			<field name="total_amount" type="decimal" />
			<field name="goods_type" type="string" />
			<field name="trade_no" type="string" />
			<field name="seller_id" type="string" />
			<field name="passback_params" type="string" />
			<field name="po_id" type="int" />	
            <field name="done" type="int" />
            <field name="datepoint" type="datetime"/>
            <field name="datepoint2" type="datetime" />
		</entity>
		
		<entity description="insert_zfb_order_info table" name="insert_zfb_order_info">
			<field name="subject" type="string" />
			<field name="body" type="string" />
			<field name="out_trade_no" type="string" />
			<field name="timeout_express" type="string" />
			<field name="time_expire" type="string" />
			<field name="total_amount" type="decimal" />
			<field name="goods_type" type="string" />
			<field name="po_id" type="int" />	
            <field name="done" type="int" />
            <field name="datepoint" type="datetime"/>
		</entity>
		
		
		<statement name="create_zfb_order_info" resultType="uc" autoKey="zo_id">
			<![CDATA[INSERT INTO ZFB_ORDER({insert_zfb_order_info})
						SELECT MP.TYPE,MP.PRO_NAME,#out_trade_no#,#timeout_express#,#time_expire#,PO.PRICE,0,#po_id#,#done#,#datepoint#  
						FROM PRO_ORDER PO JOIN MAJOR_PRODUCT MP ON MP.MP_ID = PO.MP_ID WHERE PO.PO_ID =#po_id#
			]]>
			<parameter name="timeout_express" type="string" />
			<parameter name="time_expire" type="string" />
			<parameter name="out_trade_no" type="string" />
			<parameter name="po_id" type="int" />	
            <parameter name="done" type="int" />
            <parameter name="datepoint" type="datetime"/>
		</statement>
		
		<statement name="update_xfb_service_passback_params" resultType="uc">
			<![CDATA[UPDATE ZFB_ORDER
					 SET
					 	PASSBACK_PARAMS = #passback_params#
					 WHERE ZO_ID = #zo_id#
			]]>
			<parameter name="zo_id" type="int" />
			<parameter name="passback_params" type="string" />
		</statement>
		
		<statement name="query_zfb_order_info" resultType="entity"
			entityName="zfb_order_info">
			<![CDATA[SELECT {zfb_order_info}
					 FROM ZFB_ORDER
					 WHERE ZO_ID = #zo_id#
			]]>
			<parameter name="zo_id" type="int" />
		</statement>
		
	</module>
</root>

=== isabella87/xrsrv/src/xr_statements.xml
<?xml version="1.0" encoding="utf-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="../lib/statements.xsd">
	<include src="AccUserReg.xml" />
	<include src="AccPersonInfo.xml" />
	<include src="AccCorpInfo.xml" />
	<include src="AccMsg.xml" />
	<include src="AppInfo.xml" />
	<include src="AccUserRegPwdHistory.xml" />
	<include src="MajorProduct.xml" />
	<include src="MajorService.xml" />
	<include src="ProOrder.xml" />
	<include src="CmNotice.xml" />
	<include src="MaintenanceMan.xml" />
	<include src="ZfbService.xml" />
	<include src="ZfbOrder.xml" />
	<include src="MyDict.xml" />
</root>

=== isabella87/xrsrv/src/AccCorpInfo.xml
<?xml version="1.0" encoding="utf-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../lib/statements.xsd">
	<module description="acc_corp_info module" name="acc_corp_info">
       <entity description="acc_corp_info table" name="acc_corp_info">
			<field name="au_id" type="int" />
			<field name="login_name" type="string" />
			<field name="reg_time" type="datetime" />
			<field name="org_name" type="string" />
			<field name="buss_lic" type="string" />
			<field name="tax_lic" type="string" />
			<field name="org_code_no" type="string" />	
            <field name="law_name" type="string" />
            <field name="law_id_card" type="string" />
            <field name="acc_user_name" type="string" />
            <field name="account" type="string" />
            <field name="acc_bank" type="string" />
            <field name="create_time" type="datetime" />
            <field name="update_time" type="datetime" />
            <field name="mobile" type="string" />
            <field name="real_name" type="string" />
            <field name="position" type="string" />
            <field name="id_card" type="string" />
            <field name="company" type="string" />
            <field name="company_type" type="string" />
			<field name="address" type="string" />
			<field name="postal_code" type="string" />
			<field name="home_phone" type="string" />
			<field name="qq_number" type="string" />
			<field name="email" type="string" />
			<field name="status" type="int" />
			<field name="jx_status" type="int" />
			<field name="user_code" type="string" />
		    <field name="user_type" type="int" />
		    <field name="allow_invest" type="int" />
		    <field name="allow_borrow" type="int" />
		</entity>
		
		<statement name="create_acc_corp_info" resultType="uc">
			<![CDATA[INSERT INTO ACC_CORP_INFO(AU_ID, REAL_NAME, ID_CARD, CREATE_TIME)
				     VALUES(#au_id#, #real_name#, #id_card#, SYSDATE())
			]]>
			<parameter name="au_id" type="int" />
			<parameter name="real_name" type="string" />
			<parameter name="id_card" type="string" />
		</statement>
		
		<statement name="query_acc_corp_info_list" resultType="entities"
			entityName="acc_corp_info">
			<![CDATA[SELECT ACI.AU_ID, AUR.LOGIN_NAME, AUR.REG_TIME, ACI.ORG_NAME, ACI.BUSS_LIC, ACI.TAX_LIC, ACI.ORG_CODE_NO, ACI.LAW_NAME,
		             ACI.LAW_ID_CARD, ACI.ACC_USER_NAME, ACI.ACCOUNT, ACI.ACC_BANK, ACI.CREATE_TIME, ACI.UPDATE_TIME, AUR.MOBILE, ACI.REAL_NAME,
		             ACI.POSITION, ACI.ID_CARD, ACI.COMPANY, ACI.COMPANY_TYPE, ACI.ADDRESS, ACI.POSTAL_CODE, ACI.HOME_PHONE, ACI.QQ_NUMBER, 
		             ACI.EMAIL, AUR.STATUS, IF(AJU.DATEPOINT,0,1) JX_STATUS, AUR.USER_CODE, AUR.USER_TYPE, AUR.ALLOW_INVEST, AUR.ALLOW_BORROW
					 FROM ACC_CORP_INFO ACI 
				     JOIN ACC_USER_REG AUR ON ACI.AU_ID = AUR.AU_ID
				     LEFT JOIN ACC_JX_USER AJU ON ACI.AU_ID = AJU.AU_ID
			]]>
			<dynamic prepend="WHERE">
				<isNotEmpty parameter="start_reg_time">
					<![CDATA[AUR.REG_TIME >= #start_reg_time#]]>
				</isNotEmpty>
				<isNotEmpty parameter="end_reg_time">
					<![CDATA[AUR.REG_TIME <= #end_reg_time#]]>
				</isNotEmpty>
				<isNotEmpty parameter="start_audit_time">
					<![CDATA[AUR.AUDIT_TIME >= #start_audit_time#]]>
				</isNotEmpty>
				<isNotEmpty parameter="end_audit_time">
					<![CDATA[AUR.AUDIT_TIME <= #end_audit_time#]]>
				</isNotEmpty>
				<isNotEmpty parameter="status">
					<![CDATA[AUR.STATUS = #status#]]>
				</isNotEmpty>
			    <isNotEmpty parameter="jx_status">
					<![CDATA[IF(AJU.DATEPOINT,0,1) = #jx_status#]]>
				</isNotEmpty>
				<isNotEmpty parameter="login_name">
					<![CDATA[AUR.LOGIN_NAME LIKE #login_name#]]>
				</isNotEmpty>
				<isNotEmpty parameter="real_name">
					<![CDATA[ACI.REAL_NAME LIKE #real_name#]]>
				</isNotEmpty>
				<isNotEmpty parameter="mobile">
					<![CDATA[AUR.MOBILE LIKE #mobile#]]>
				</isNotEmpty>
				<isNotEmpty parameter="auditor">
					<![CDATA[AUR.AUDITOR LIKE #auditor#]]>
				</isNotEmpty>
			</dynamic>
			<![CDATA[ORDER BY AUR.AU_ID]]>
			<parameter name="start_reg_time" type="datetime" />
			<parameter name="end_reg_time" type="datetime" />
			<parameter name="start_audit_time" type="datetime" />
			<parameter name="end_audit_time" type="datetime" />
			<parameter name="status" type="int" />
			<parameter name="jx_status" type="int"/>
			<parameter name="login_name" type="string" match="contains" />
			<parameter name="real_name" type="string" match="contains" />
			<parameter name="mobile" type="string" match="contains" />
			<parameter name="auditor" type="string" match="contains" />
		</statement>
	
		<statement name="update_corp_account_info_by_au_id" resultType="uc">
		     <![CDATA[UPDATE ACC_CORP_INFO
				     SET LAW_NAME = #law_name#,
				     LAW_ID_CARD = #law_id_card#,
				     BUSS_LIC = #buss_lic#,
				     TAX_LIC = #tax_lic#,
				     ORG_CODE_NO = #org_code_no#,
				     ACC_USER_NAME = #acc_user_name#,
				     ACCOUNT = #account#,
				     ACC_BANK = #acc_bank#,
				     ORG_NAME = #org_name#,
					 UPDATE_TIME = SYSDATE
					 WHERE AU_ID = #au_id#
			 ]]>
		     <parameter name="au_id" type="int"/>
		     <parameter name="law_name" type="string"/>
		     <parameter name="law_id_card" type="string"/>
		     <parameter name="buss_lic" type="string"/>
		     <parameter name="tax_lic" type="string"/>
		     <parameter name="org_code_no" type="string"/>
		     <parameter name="acc_user_name" type="string"/>
		     <parameter name="account" type="string"/>
		     <parameter name="acc_bank" type="string"/>
		     <parameter name="org_name" type="string"/>
		</statement>
		
		<statement name="update_basic_info_by_au_id" resultType="uc">
		   <![CDATA[UPDATE ACC_CORP_INFO
				     SET ADDRESS = #address#,
				     HOME_PHONE = #home_phone#,
				     POSTAL_CODE = #postal_code#,
				     POSITION = #position#,
				     COMPANY = #company#,
				     COMPANY_TYPE = #company_type#,
				     QQ_NUMBER = #qq_number#,
					 UPDATE_TIME = SYSDATE()
					 WHERE AU_ID = #au_id#
			 ]]>
		     <parameter name="au_id" type="int"/>
		     <parameter name="address" type="string"/>
		     <parameter name="home_phone" type="string"/>
		     <parameter name="postal_code" type="string"/>
		     <parameter name="position" type="string"/>
		     <parameter name="company" type="string"/>
		     <parameter name="company_type" type="string"/>
		     <parameter name="qq_number" type="string"/>
		</statement>
		
		<statement name="exist_acc_corp_info_by_id_card" resultType="bool">
			<![CDATA[SELECT CASE WHEN EXISTS (SELECT AU_ID FROM ACC_CORP_INFO WHERE ID_CARD = #id_card#) THEN 1
				     	    ELSE 0 END 
				     FROM DUAL
			]]>
			<parameter name="id_card" type="string" />
		</statement>
		
		<statement name="query_acc_corp_info_by_au_id" entityName="acc_corp_info" resultType="entity">
		    <![CDATA[SELECT ACI.AU_ID, AUR.LOGIN_NAME, AUR.REG_TIME, ACI.ORG_NAME, ACI.BUSS_LIC, ACI.TAX_LIC, ACI.ORG_CODE_NO, ACI.LAW_NAME,
		             ACI.LAW_ID_CARD, ACI.ACC_USER_NAME, ACI.ACCOUNT, ACI.ACC_BANK, ACI.CREATE_TIME, ACI.UPDATE_TIME, AUR.MOBILE, ACI.REAL_NAME,
		             ACI.POSITION, ACI.ID_CARD, ACI.COMPANY, ACI.COMPANY_TYPE, ACI.ADDRESS, ACI.POSTAL_CODE, ACI.HOME_PHONE, ACI.QQ_NUMBER, 
		             ACI.EMAIL, AUR.STATUS, IF(AJU.DATEPOINT,0,1) JX_STATUS, AUR.USER_CODE, AUR.USER_TYPE, AUR.ALLOW_INVEST, AUR.ALLOW_BORROW
		             FROM ACC_CORP_INFO ACI
		             JOIN ACC_USER_REG AUR ON ACI.AU_ID = AUR.AU_ID
		             LEFT JOIN ACC_JX_USER AJU ON ACI.AU_ID = AJU.AU_ID
		             WHERE ACI.AU_ID = #au_id#
			]]>
		    <parameter name="au_id" type="int" />
		</statement>
		
		<statement name="update_email_by_au_id" resultType="uc">
		    <![CDATA[UPDATE ACC_CORP_INFO
		             SET EMAIL = #email#,
		             UPDATE_TIME = SYSDATE()
					 WHERE AU_ID = #au_id#
					 AND NOT EXISTS (SELECT 1 FROM ACC_PERSON_INFO WHERE EMAIL = #email#
					           UNION SELECT 1 FROM ACC_CORP_INFO WHERE EMAIL = #email#) 
		    ]]>
		    <parameter name="au_id" type="int" />
		    <parameter name="email" type="string" />
		</statement>
		
		<statement name="query_acc_corp_info_by_login_name_or_mobile"
			resultType="entity" entityName="acc_corp_info">
			<![CDATA[SELECT ACI.AU_ID, AUR.LOGIN_NAME, AUR.REG_TIME, ACI.ORG_NAME, ACI.BUSS_LIC, ACI.TAX_LIC, ACI.ORG_CODE_NO, ACI.LAW_NAME,
		             ACI.LAW_ID_CARD, ACI.ACC_USER_NAME, ACI.ACCOUNT, ACI.ACC_BANK, ACI.CREATE_TIME, ACI.UPDATE_TIME, AUR.MOBILE, ACI.REAL_NAME,
		             ACI.POSITION, ACI.ID_CARD, ACI.COMPANY, ACI.COMPANY_TYPE, ACI.ADDRESS, ACI.POSTAL_CODE, ACI.HOME_PHONE, ACI.QQ_NUMBER, 
		             ACI.EMAIL, AUR.STATUS, IF(AJU.DATEPOINT,0,1) JX_STATUS, AUR.USER_CODE, AUR.USER_TYPE, AUR.ALLOW_INVEST, AUR.ALLOW_BORROW
				     FROM ACC_CORP_INFO ACI  
				     JOIN ACC_USER_REG AUR ON ACI.AU_ID = AUR.AU_ID
				     LEFT JOIN ACC_JX_USER AJU ON ACI.AU_ID = AJU.AU_ID
				     WHERE AUR.LOGIN_NAME = #login_name_or_mobile# OR AUR.MOBILE=#login_name_or_mobile#
			]]>
			<parameter name="login_name_or_mobile" type="string" />
		</statement>
	</module>
</root>
