=== isabella87/xrsrv/lib/statements.xsd
<?xml version="1.0" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified">

	<xsd:element name="root">
		<xsd:complexType>
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element name="module" type="moduleType" />
				<xsd:element name="include" type="includeType" />
			</xsd:choice>
		</xsd:complexType>
	</xsd:element>

	<xsd:complexType name="moduleType">
		<xsd:sequence minOccurs="0" maxOccurs="1">
			<xsd:element name="entity" type="entityType" minOccurs="0"
				maxOccurs="unbounded" />
			<xsd:element name="sql" type="sqlFragmentType" minOccurs="0"
				maxOccurs="unbounded" />
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element name="statement" type="statementType" />
				<xsd:element name="stmt" type="statementType" />
			</xsd:choice>
		</xsd:sequence>
		<xsd:attribute name="name" type="identityName" use="required" />
		<xsd:attribute name="package" type="packageName" use="optional"
			default="" />
		<xsd:attribute name="description" type="xsd:normalizedString"
			use="optional" default="" />
	</xsd:complexType>

	<xsd:complexType name="includeType">
		<xsd:attribute name="src" type="xsd:string" use="required" />
	</xsd:complexType>

	<xsd:complexType name="entityType">
		<xsd:choice minOccurs="1" maxOccurs="unbounded">
			<xsd:element name="field" type="fieldType" />
		</xsd:choice>
		<xsd:attribute name="name" type="identityName" use="required" />
		<xsd:attribute name="description" type="xsd:normalizedString"
			use="optional" default="" />
	</xsd:complexType>

	<xsd:complexType name="fieldType">
		<xsd:attribute name="name" type="identityName" use="required" />
		<xsd:attribute name="type" type="fieldTypeType" use="optional"
			default="string" />
		<xsd:attribute name="key" type="boolean" use="optional"
			default="false" />
		<xsd:attribute name="description" type="xsd:normalizedString"
			use="optional" default="" />
		<xsd:attribute name="defaultValue" type="xsd:normalizedString"
			use="optional" default="" />
	</xsd:complexType>

	<xsd:complexType name="sqlFragmentType" mixed="true">
		<xsd:attribute name="name" type="identityName" use="required" />
	</xsd:complexType>

	<xsd:complexType name="statementType" mixed="true">
		<xsd:sequence>
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element name="sqlRef" type="sqlReferenceType"
					minOccurs="0" maxOccurs="unbounded" />
				<xsd:element name="dynamic" type="dynamicStatementType"
					minOccurs="0" maxOccurs="unbounded" />
			</xsd:choice>
			<xsd:element name="parameter" type="parameterType"
				minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
		<xsd:attribute name="name" type="identityName" use="required" />
		<xsd:attribute name="allowPaging" type="boolean"
			default="auto" />
		<xsd:attribute name="commandType" type="statementCommandTypeType"
			default="text" />
		<xsd:attribute name="resultType" type="statementResultTypeType"
			default="updated-count" />
		<xsd:attribute name="entityName" type="identityName"
			use="optional" />
		<xsd:attribute name="autoKey" type="autoKeyName" use="optional" />
		<xsd:attribute name="readonly" type="boolean" default="auto" />
		<xsd:attribute name="description" type="xsd:normalizedString"
			use="optional" default="" />
	</xsd:complexType>

	<xsd:complexType name="sqlReferenceType">
		<xsd:attribute name="name" type="identityName" use="required" />
	</xsd:complexType>

	<xsd:simpleType name="statementCommandTypeType">
		<xsd:restriction base="xsd:normalizedString">
			<xsd:enumeration value="text" />
			<!-- store procedure // -->
			<xsd:enumeration value="sp" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:complexType name="dynamicStatementType">
		<xsd:choice minOccurs="1" maxOccurs="unbounded">
			<xsd:element name="isNull" type="dynamicStatementTextType" />
			<xsd:element name="isNotNull" type="dynamicStatementTextType" />
			<xsd:element name="isEmpty" type="dynamicStatementTextType" />
			<xsd:element name="isNotEmpty" type="dynamicStatementTextType" />
			<xsd:element name="isNullOrEmpty" type="dynamicStatementTextType" />
			<xsd:element name="equals" type="dynamicStatementTextType" />
			<xsd:element name="notEquals" type="dynamicStatementTextType" />
			<xsd:element name="in" type="dynamicStatementTextType" />
			<xsd:element name="notIn" type="dynamicStatementTextType" />
		</xsd:choice>
		<xsd:attribute name="prepend" type="xsd:normalizedString"
			use="optional" default="" />
		<xsd:attribute name="append" type="xsd:normalizedString"
			use="optional" default="" />
		<xsd:attribute name="joint" type="xsd:normalizedString"
			use="optional" default="AND" />
	</xsd:complexType>

	<xsd:complexType name="dynamicStatementTextType" mixed="true">
		<xsd:attribute name="parameter" type="identityName" use="required" />
		<xsd:attribute name="value" type="xsd:normalizedString"
			default="" />
	</xsd:complexType>

	<xsd:complexType name="parameterType">
		<xsd:attribute name="name" type="identityName" use="required" />
		<xsd:attribute name="type" type="parameterTypeType" use="required" />
		<xsd:attribute name="size" type="columnSizeType" use="optional"
			default="0">
		</xsd:attribute>
		<xsd:attribute name="match" type="parameterMatchType"
			default="exact" />
		<xsd:attribute name="description" type="xsd:normalizedString"
			use="optional" default="" />
	</xsd:complexType>

	<xsd:simpleType name="columnSizeType">
		<xsd:restriction base="xsd:nonNegativeInteger">
			<xsd:minInclusive fixed="true" value="0" />
			<xsd:maxInclusive fixed="true" value="4000" />
			<xsd:whiteSpace value="collapse" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="parameterTypeType">
		<xsd:restriction base="xsd:normalizedString">
			<xsd:enumeration value="string" />
			<xsd:enumeration value="int" />
			<xsd:enumeration value="integer" />
			<xsd:enumeration value="money" />
			<xsd:enumeration value="decimal" />
			<xsd:enumeration value="currency" />
			<xsd:enumeration value="datetime" />
			<xsd:enumeration value="date" />
			<xsd:enumeration value="start-date" />
			<xsd:enumeration value="start-month" />
			<xsd:enumeration value="start-year" />
			<xsd:enumeration value="end-date" />
			<xsd:enumeration value="end-month" />
			<xsd:enumeration value="end-year" />
			<xsd:enumeration value="double" />
			<xsd:enumeration value="real" />
			<xsd:enumeration value="bit" />
			<xsd:enumeration value="bool" />
			<xsd:enumeration value="boolean" />
			<xsd:enumeration value="binary" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="parameterMatchType">
		<xsd:restriction base="xsd:normalizedString">
			<xsd:enumeration value="exact" />
			<xsd:enumeration value="starts-with" />
			<xsd:enumeration value="ends-with" />
			<xsd:enumeration value="contains" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="fieldTypeType">
		<xsd:restriction base="xsd:normalizedString">
			<xsd:enumeration value="string" />
			<xsd:enumeration value="big-string" />
			<xsd:enumeration value="int" />
			<xsd:enumeration value="integer" />
			<xsd:enumeration value="money" />
			<xsd:enumeration value="decimal" />
			<xsd:enumeration value="currency" />
			<xsd:enumeration value="datetime" />
			<xsd:enumeration value="real" />
			<xsd:enumeration value="double" />
			<xsd:enumeration value="bit" />
			<xsd:enumeration value="bool" />
			<xsd:enumeration value="boolean" />
			<xsd:enumeration value="binary" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="statementResultTypeType">
		<xsd:restriction base="xsd:normalizedString">
			<!-- Entity -->
			<xsd:enumeration value="entities" />
			<xsd:enumeration value="entity" />
			<!-- Scalar -->
			<xsd:enumeration value="string" />
			<xsd:enumeration value="int" />
			<xsd:enumeration value="integer" />
			<xsd:enumeration value="money" />
			<xsd:enumeration value="decimal" />
			<xsd:enumeration value="currency" />
			<xsd:enumeration value="datetime" />
			<xsd:enumeration value="date" />
			<xsd:enumeration value="double" />
			<xsd:enumeration value="bit" />
			<xsd:enumeration value="bool" />
			<xsd:enumeration value="boolean" />
			<xsd:enumeration value="binary" />
			<xsd:enumeration value="array" />
			<!-- List -->
			<xsd:enumeration value="list-string" />
			<xsd:enumeration value="list-int" />
			<xsd:enumeration value="list-integer" />
			<xsd:enumeration value="list-money" />
			<xsd:enumeration value="list-decimal" />
			<xsd:enumeration value="list-currency" />
			<xsd:enumeration value="list-datetime" />
			<xsd:enumeration value="list-date" />
			<xsd:enumeration value="list-double" />
			<xsd:enumeration value="list-bit" />
			<xsd:enumeration value="list-bool" />
			<xsd:enumeration value="list-boolean" />
			<xsd:enumeration value="list-binary" />
			<xsd:enumeration value="list-array" />
			<!-- Update -->
			<xsd:enumeration value="uc" />
			<xsd:enumeration value="updated-count" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="boolean">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="auto" />
			<xsd:enumeration value="0" />
			<xsd:enumeration value="1" />
			<xsd:enumeration value="yes" />
			<xsd:enumeration value="no" />
			<xsd:enumeration value="true" />
			<xsd:enumeration value="false" />
			<xsd:enumeration value="on" />
			<xsd:enumeration value="off" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="text">
		<xsd:restriction base="xsd:string">
			<xsd:minLength value="1" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="identityName">
		<xsd:restriction base="xsd:normalizedString">
			<xsd:minLength value="1" />
			<xsd:pattern value="[\w_]+" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="autoKeyName">
		<xsd:restriction base="xsd:normalizedString">
			<xsd:minLength value="1" />
			<xsd:pattern value="([\w_]+)|\*" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="packageName">
		<xsd:restriction base="xsd:normalizedString">
			<xsd:minLength value="0" />
			<xsd:pattern value="[\w_]*" />
		</xsd:restriction>
	</xsd:simpleType>
</xsd:schema>

=== isabella87/xrsrv/src/AccPersonInfo.xml
<?xml version="1.0" encoding="utf-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../lib/statements.xsd">
	<module description="acc_person_info_ module" name="acc_person_info">
         <entity description="acc_person_info table" name="acc_person_info">
			<field name="au_id" type="int" />
			<field name="login_name" type="string" />
			<field name="reg_time" type="datetime" />
			<field name="address" type="string" />
			<field name="home_phone" type="string" />
			<field name="postal_code" type="string" />
			<field name="position" type="string" />
			<field name="company" type="string" />
			<field name="company_type" type="string" />
			<field name="qq_number" type="string" />
			<field name="update_time" type="datetime" />
			<field name="create_time" type="datetime" />
			<field name="real_name" type="string" />
			<field name="id_card" type="string" />
			<field name="mobile" type="string" />
			<field name="email" type="string" />
			<field name="status" type="int" />
			<field name="user_code" type="string" />
			<field name="user_type" type="int" />
			<field name="org_code" type="string" />
			<field name="mm_id" type="int" />
			<field name="mm_file_id" type="int" />
		</entity>
		
		<statement name="create_acc_person_info" resultType="uc">
			<![CDATA[INSERT INTO ACC_PERSON_INFO(AU_ID, REAL_NAME, ID_CARD, ORG_CODE, CREATE_TIME)
			         VALUES(#au_id#, #real_name#, #id_card#, #org_code#, SYSDATE())
			]]>
			<parameter name="au_id" type="int" />
			<parameter name="real_name" type="string" />
			<parameter name="id_card" type="string" />
			<parameter name="org_code" type="string" />
		</statement>
		
		<statement name="update_basic_info_by_au_id" resultType="uc">
		     <![CDATA[UPDATE ACC_PERSON_INFO
				     SET ADDRESS = #address#,
				     HOME_PHONE = #home_phone#,
				     POSTAL_CODE = #postal_code#,
				     POSITION = #position#,
				     COMPANY = #company#,
				     COMPANY_TYPE = #company_type#,
				     QQ_NUMBER = #qq_number#,
					 UPDATE_TIME = SYSDATE()
					 WHERE AU_ID = #au_id#
			 ]]>
		     <parameter name="au_id" type="int"/>
		     <parameter name="address" type="string"/>
		     <parameter name="home_phone" type="string"/>
		     <parameter name="postal_code" type="string"/>
		     <parameter name="position" type="string"/>
		     <parameter name="company" type="string"/>
		     <parameter name="company_type" type="string"/>
		     <parameter name="qq_number" type="string"/>
		</statement>

		<statement name="exist_acc_person_info_by_id_card"
			resultType="bool">
			<![CDATA[SELECT CASE WHEN EXISTS (SELECT 1 FROM ACC_PERSON_INFO WHERE ID_CARD = #id_card#) THEN 1
				     	    ELSE 0 END 
				     FROM DUAL
			]]>
			<parameter name="id_card" type="string" />
		</statement>
		
		<statement name="query_acc_person_info_by_au_id" entityName="acc_person_info" resultType="entity">
		   <![CDATA[SELECT API.AU_ID, AUR.LOGIN_NAME, AUR.REG_TIME, API.ADDRESS, API.HOME_PHONE, API.POSTAL_CODE, API.POSITION, API.COMPANY,
		            API.COMPANY_TYPE, API.QQ_NUMBER,  API.UPDATE_TIME, API.CREATE_TIME, API.REAL_NAME, API.ID_CARD, AUR.MOBILE, API.EMAIL,
		            AUR.STATUS, AUR.USER_CODE, AUR.USER_TYPE, API.ORG_CODE,AUR.MM_ID,IFNULL(FF.FILE_ID,0) MM_FILE_ID
		            FROM ACC_PERSON_INFO API
		            JOIN ACC_USER_REG AUR ON API.AU_ID = AUR.AU_ID
		            LEFT JOIN FS_FILE FF ON AUR.MM_ID = FF.OBJECT_ID AND FF.FILE_TYPE = 11
		            WHERE API.AU_ID = #au_id#]]>
		   <parameter name="au_id" type="int" />
		</statement>
		
		<statement name="update_email_by_au_id" resultType="uc">
		    <![CDATA[UPDATE ACC_PERSON_INFO
		             SET EMAIL = #email#,
		             UPDATE_TIME = SYSDATE()
					 WHERE AU_ID = #au_id#
					 AND NOT EXISTS (SELECT 1 FROM ACC_PERSON_INFO WHERE EMAIL = #email#
					           UNION SELECT 1 FROM ACC_CORP_INFO WHERE EMAIL = #email#) 
		    ]]>
		    <parameter name="au_id" type="int" />
		    <parameter name="email" type="string" />
		</statement>
		
		<statement name="update_name_and_id_card_by_au_id" resultType="uc">
		    <![CDATA[
	    		 UPDATE ACC_PERSON_INFO
	             	SET REAL_NAME = #real_name#, ID_CARD = #id_card#
				  WHERE AU_ID = #au_id#
		    ]]>
		    <parameter name="au_id" type="int" />
		    <parameter name="real_name" type="string" />
		    <parameter name="id_card" type="string" />
		</statement>
			
		<statement name="query_acc_person_info_list" resultType="entities"
			entityName="acc_person_info" allowPaging="true">
			<![CDATA[SELECT AUR.AU_ID, AUR.LOGIN_NAME, AUR.REG_TIME, API.ADDRESS, API.HOME_PHONE, API.POSTAL_CODE, API.POSITION, API.COMPANY,
			         API.COMPANY_TYPE, API.QQ_NUMBER, API.UPDATE_TIME, API.CREATE_TIME, API.REAL_NAME, API.ID_CARD, AUR.MOBILE, API.EMAIL, 
			         AUR.STATUS,  AUR.USER_CODE, AUR.USER_TYPE, API.ORG_CODE,AUR.MM_ID,IFNULL(FF.FILE_ID,0) MM_FILE_ID
			         FROM ACC_PERSON_INFO API
			         JOIN ACC_USER_REG AUR ON AUR.AU_ID = API.AU_ID
			         LEFT JOIN FS_FILE FF ON AUR.MM_ID = FF.OBJECT_ID AND FF.FILE_TYPE = 11
			]]>
			<dynamic prepend="WHERE">
				<isNotEmpty parameter="start_time">
					<![CDATA[AUR.REG_TIME >= #start_time#]]>
				</isNotEmpty>
				<isNotEmpty parameter="end_time">
					<![CDATA[AUR.REG_TIME <= #end_time#]]>
				</isNotEmpty>
				<isNotEmpty parameter="status">
					<![CDATA[AUR.STATUS = #status#]]>
				</isNotEmpty>
				<isNotEmpty parameter="login_name">
					<![CDATA[AUR.LOGIN_NAME LIKE #login_name#]]>
				</isNotEmpty>
				<isNotEmpty parameter="real_name">
					<![CDATA[API.REAL_NAME LIKE #real_name#]]>
				</isNotEmpty>
				<isNotEmpty parameter="mobile">
					<![CDATA[AUR.MOBILE LIKE #mobile#]]>
				</isNotEmpty>
				<isNotEmpty parameter="recommend_user_code">
					<![CDATA[AUR.RECOMMEND_USER_CODE LIKE #recommend_user_code#]]>
				</isNotEmpty>
			</dynamic>
			<![CDATA[ORDER BY AUR.AU_ID]]>
			<parameter name="start_time" type="datetime" />
			<parameter name="end_time" type="datetime" />
			<parameter name="status" type="int" />
			<parameter name="login_name" type="string" match="contains" />
			<parameter name="real_name" type="string" match="contains" />
			<parameter name="mobile" type="string" match="contains" />
			<parameter name="recommend_user_code" type="string" match="contains" />
		</statement>
			
		<statement name="query_acc_person_info_by_login_name_or_mobile"
			resultType="entity" entityName="acc_person_info">
			<![CDATA[SELECT AUR.AU_ID, AUR.LOGIN_NAME, AUR.REG_TIME, API.ADDRESS, API.HOME_PHONE, API.POSTAL_CODE, API.POSITION, API.COMPANY,
			         API.COMPANY_TYPE, API.QQ_NUMBER, API.UPDATE_TIME, API.CREATE_TIME, API.REAL_NAME, API.ID_CARD, AUR.MOBILE, API.EMAIL,
			         AUR.STATUS, AUR.USER_CODE, AUR.USER_TYPE, API.ORG_CODE,AUR.MM_ID,IFNULL(FF.FILE_ID,0) MM_FILE_ID
			         FROM ACC_PERSON_INFO API
			         JOIN ACC_USER_REG AUR ON API.AU_ID = AUR.AU_ID
			         LEFT JOIN FS_FILE FF ON AUR.MM_ID = FF.OBJECT_ID AND FF.FILE_TYPE = 11
        		     WHERE AUR.MOBILE = #login_name_or_mobie# OR AUR.LOGIN_NAME = #login_name_or_mobie#
        	]]>
			<parameter name="login_name_or_mobie" type="string" />
		</statement>
		
	</module>
</root>

=== isabella87/xrsrv/src/AccMsg.xml
<?xml version="1.0" encoding="utf-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../lib/statements.xsd">
	<module description="acc_msg module" name="acc_msg">
	
		<statement name="create_lost_pwd_code" resultType="uc" autoKey="m_id">
			<![CDATA[INSERT INTO MSG_LOST_PWD (MOBILE, V_CODE, DATEPOINT,STATUS)
					VALUES ( #mobile#, #v_code#, #datepoint#,0)
			]]>
			<parameter name="mobile" type="string" />
			<parameter name="v_code" type="string" />
			<parameter name="datepoint" type="datetime" />
		</statement>

		<statement name="check_lost_pwd_code" resultType="boolean">
			<![CDATA[SELECT 
						CASE WHEN EXISTS(SELECT * FROM MSG_LOST_PWD WHERE MOBILE = #mobile# AND V_CODE = #v_code#
							AND DATEPOINT > #datepoint# AND STATUS = 0) THEN 1
						ELSE 0 END 
					 FROM DUAL
			]]>
			<parameter name="mobile" type="string" />
			<parameter name="v_code" type="string" />
			<parameter name="datepoint" type="datetime" />
		</statement>
		
		<statement name="update_lost_pwd_code" resultType="uc">
			<![CDATA[
				UPDATE MSG_LOST_PWD SET STATUS=1 
				WHERE MOBILE=#mobile# AND V_CODE=#v_code# AND STATUS=0
			]]>
			<parameter name="mobile" type="string"/>
			<parameter name="v_code" type="string"/>
		</statement>
		
		<statement name="clear_msg_lost_pwd" resultType="uc">
			<![CDATA[UPDATE MSG_LOST_PWD SET STATUS = 1 
					WHERE MOBILE = #mobile#
			]]>
			<parameter name="mobile" type="string" />
		</statement>
		
		<statement name="clear_msg_reg_account" resultType="updated-count">
			<![CDATA[
				DELETE FROM MSG_REG_USER 
				 WHERE MOBILE=#mobile#
			]]>
			<parameter name="mobile" type="string"/>
		</statement>
		
		<statement name="create_reg_account_code" resultType="updated-count" autoKey="m_id">
			<![CDATA[
				INSERT INTO MSG_REG_USER(MOBILE ,V_CODE ,DATEPOINT,STATUS) 
				VALUES(#mobile#,#v_code#,#datepoint#,0)
			]]>
			<parameter name="mobile" type="string"/>
			<parameter name="v_code" type="string"/>
			<parameter name="datepoint" type="datetime"/>
		</statement>
		
		<statement name="check_reg_account_code" resultType="bool">
			<![CDATA[
				SELECT CASE WHEN EXISTS(SELECT * FROM MSG_REG_USER WHERE MOBILE=#mobile#  AND STATUS=0 AND V_CODE=#v_code# AND DATEPOINT>=#date#) THEN 1
				ELSE 0
				END
				FROM DUAL
			]]>
			<parameter name="mobile" type="string"/>
			<parameter name="v_code" type="string"/>
			<parameter name="date" type="datetime"/>
		</statement>
		
		<statement name="update_acvice_code_status" resultType="updated-count">
			<![CDATA[
				UPDATE MSG_REG_USER SET STATUS=1 
				WHERE MOBILE=#mobile# AND V_CODE=#v_code# and STATUS = 0
			]]>
			<parameter name="mobile" type="string"/>
			<parameter name="v_code" type="string"/>
		</statement>
		
		<statement name="create_change_mobile_code" resultType="updated-count" autoKey="m_id">
			<![CDATA[
				INSERT INTO MSG_CHANGE_MOBILE (MOBILE, V_CODE, DATEPOINT,STATUS)
				VALUES (#mobile#, #v_code#, #datepoint#,0)
			]]>
			<parameter name="mobile" type="string"/>
			<parameter name="v_code" type="string"/>
			<parameter name="datepoint" type="datetime"/>
		</statement>
		
		<statement name="update_change_mobile_status" resultType="updated-count">
			<![CDATA[
				UPDATE MSG_CHANGE_MOBILE SET STATUS=1 
				WHERE MOBILE=#mobile# AND V_CODE=#v_code# AND STATUS=0
			]]>
			<parameter name="mobile" type="string"/>
			<parameter name="v_code" type="string"/>
		</statement>
		
		<statement name="check_change_mobile_code" resultType="boolean">
			<![CDATA[
				SELECT CASE WHEN EXISTS(SELECT * FROM MSG_CHANGE_MOBILE WHERE MOBILE = #mobile# AND V_CODE = #v_code#
					AND DATEPOINT > #datepoint# AND STATUS = 0) THEN 1
					ELSE 0 END 
				FROM DUAL
			]]>
			<parameter name="mobile" type="string" />
			<parameter name="v_code" type="string" />
			<parameter name="datepoint" type="datetime" />
		</statement>
		
		<statement name="create_sms_ym_code" resultType="updated-count" autoKey="ms_id">
			<![CDATA[ 
				INSERT INTO MSG_SMS_YM (MOBILE, CONTENT, T_CODE, P_ID, DATEPOINT)
				VALUES ( #mobile#, #content#, #t_code#, #p_id#, #datepoint#)
			]]>
			<parameter name="mobile" type="string" />
			<parameter name="content" type="string" />
			<parameter name="t_code" type="int" />
			<parameter name="p_id"	type="int" />
			<parameter name="datepoint" type="datetime" /> 
		</statement>	
	</module>
</root>
